#!/bin/zsh

# Define the base directory
base_dir="$HOME/Workspace"

# Define the directory structure
directories=(
    "Developer Resources/Java/Core/Basics"
    "Developer Resources/Java/Core/Advanced"
    "Developer Resources/Java/Core/Design Patterns"
    "Developer Resources/Java/Frameworks/Spring/Core"
    "Developer Resources/Java/Frameworks/Spring/Spring Boot"
    "Developer Resources/Java/Frameworks/Spring/Spring MVC"
    "Developer Resources/Java/Frameworks/Hibernate"
    "Developer Resources/Java/Libraries/Apache Commons"
    "Developer Resources/Java/Libraries/Guava"
    "Developer Resources/Java/Best Practices"
    "Developer Resources/Algorithms/Sorting"
    "Developer Resources/Algorithms/Searching"
    "Developer Resources/Algorithms/Data Structures"
    "Developer Resources/Algorithms/Dynamic Programming"
    "Developer Resources/Software Engineering/Requirements"
    "Developer Resources/Software Engineering/Design/UML"
    "Developer Resources/Software Engineering/Design/Architectural Patterns"
    "Developer Resources/Software Engineering/Testing/Unit Testing"
    "Developer Resources/Software Engineering/Testing/Integration Testing"
    "Developer Resources/Software Engineering/Agile Methodologies"
    "Developer Resources/Databases/SQL"
    "Developer Resources/Databases/NoSQL"
    "Developer Resources/Databases/Database Design"
    "Developer Resources/Web Development/HTML"
    "Developer Resources/Web Development/CSS"
    "Developer Resources/Web Development/JavaScript"
    "Developer Resources/Web Development/Frontend Frameworks/Angular"
    "Developer Resources/Web Development/Frontend Frameworks/React"
    "Developer Resources/Web Development/Frontend Frameworks/Vue.js"
    "Developer Resources/Web Development/Backend Technologies/Node.js"
    "Developer Resources/Web Development/Backend Technologies/Express.js"
    "Developer Resources/Web Development/Backend Technologies/RESTful APIs"
    "Developer Resources/Web Development/Web Security"
    "Developer Resources/Tools/IDEs/IntelliJ IDEA"
    "Developer Resources/Tools/IDEs/Eclipse"
    "Developer Resources/Tools/IDEs/NetBeans"
    "Developer Resources/Tools/Version Control/Git"
    "Developer Resources/Tools/Version Control/Subversion"
    "Developer Resources/Tools/Build Automation/Maven"
    "Developer Resources/Tools/Build Automation/Gradle"
    "Developer Resources/Miscellaneous/Interview Preparation"
    "Developer Resources/Miscellaneous/Career Development"
    "Developer Resources/Miscellaneous/General Notes"
    "Developer Resources/SavedBlogs/Java/CoreConcepts"
    "Developer Resources/SavedBlogs/Java/BestPractices"
    "Developer Resources/SavedBlogs/Java/AdvancedTopics"
    "Developer Resources/SavedBlogs/Spring/Core"
    "Developer Resources/SavedBlogs/Spring/SpringBoot"
    "Developer Resources/SavedBlogs/Spring/SpringFramework"
    "Developer Resources/SavedBlogs/AI/MachineLearning"
    "Developer Resources/SavedBlogs/AI/DeepLearning"
    "Developer Resources/SavedBlogs/AI/AIApplications"
    "Developer Resources/SavedBlogs/APM/Concepts"
    "Developer Resources/SavedBlogs/APM/Tools"
    "Developer Resources/SavedBlogs/APM/BestPractices"
    "Developer Resources/SavedBlogs/Kubernetes/Basics"
    "Developer Resources/SavedBlogs/Kubernetes/Deployment"
    "Developer Resources/SavedBlogs/Kubernetes/AdvancedTopics"
    "Developer Resources/SavedBlogs/GeneralTech/CloudComputing"
    "Developer Resources/SavedBlogs/GeneralTech/DevOps"
    "Developer Resources/SavedBlogs/GeneralTech/EmergingTechnologies"
    "Developer Resources/SavedBlogs/Miscellaneous/ProductivityTips"
    "Developer Resources/SavedBlogs/Miscellaneous/CareerAdvice"
    "Developer Resources/SavedBlogs/Miscellaneous/GeneralBlogs"
)

# Create the directories
for dir in "${directories[@]}"; do
    mkdir -p "$base_dir/$dir"
done

echo "Directory structure created successfully."
